permissions:
  contents: read
name: Tests (unit)

on:
  push:
    branches: ["**"]
    tags-ignore: ["*"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20"
  CI: "true"

jobs:
  tests:
    name: Install, Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps (root + workspaces)
        run: npm ci

      - name: Prisma generate (apps/api)
        run: npx -w apps/api prisma generate --schema ../../prisma/schema.prisma

      - name: Build API (optional)
        run: npm --workspace apps/api run build --if-present

      - name: Run tests (unit)
        run: npm --workspace apps/api run test:ci
      - name: Show coverage summary
        run: |
          if [ -f apps/api/reports/coverage/lcov.info ]; then
            echo "LCOV generated at apps/api/reports/coverage/lcov.info"
          fi

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: junit-report
          path: apps/api/reports/junit/jest-junit.xml
          if-no-files-found: warn
          retention-days: 14

      - name: Upload coverage (lcov + html)
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: coverage
          path: |
            apps/api/reports/coverage/lcov.info
            apps/api/reports/coverage
          if-no-files-found: warn
          retention-days: 14
